### ISSUE TITLE
>=app-text/qpdf-11.0.0 breaks brgenml1 (prob others too)

### ISSUE THREAD

**Issue by joecool1029** [stefan-langenmaier/brother-overlay#113]
Since the overlay isn't in gentoo and it's not considered official I'll file here. It looks like unless there's a workaround you'll need to throw a dependency to pull a qpdf-10.x version or cups-filters will crash. 

Part of log that's probably relevant:

```
D [23/Sep/2022:17:38:07 -0400] [Job 262] pdftopdf: Last filter determined by the PPD: -; FINAL_CONTENT_TYPE: application/pdf => pdftopdf will log pages in page_log.
D [23/Sep/2022:17:38:07 -0400] [Job 262] PDF template file doesn\'t have form. It\'s okay.
D [23/Sep/2022:17:38:07 -0400] [Job 262] terminate called after throwing an instance of \'std::logic_error\'
D [23/Sep/2022:17:38:07 -0400] [Job 262] what():  QPDFCryptoProvider: request to set default provider to unknown implementation \"OPENSSL\"
D [23/Sep/2022:17:38:07 -0400] [Job 262] PID 29698 (/usr/libexec/cups/filter/bannertopdf) crashed on signal 6.
D [23/Sep/2022:17:38:07 -0400] [Job 262] Hint: Try setting the LogLevel to "debug" to find out more.
D [23/Sep/2022:17:38:07 -0400] [Job 262] Input is empty, outputting empty file.
D [23/Sep/2022:17:38:07 -0400] [Job 262] PID 29699 (/usr/libexec/cups/filter/pdftopdf) exited with no errors.
```

Rebuilding everything was no good, I have ssl and openssl flags enabled wherever I could to rule that out. Eventually trying the downgrade to <app-text/qpdf-11.0.0 worked.

**Comment by stefan-langenmaier** [comment]
Hi @joecool1029 ,

thanks for your report. Unfortunately I don't understand what's to do here and what's the cause. Could this issue be in `cups-filters` or `qpdf`?

**Comment by joecool1029** [comment]
I think it's an incompatibility between cups-filters and qpdf-11. Apparently the brother driver requires some pdf filter and this crashes when built against qpdf-11. My recommendation is to leave this issue open for some time as qpdf-11 only hit the portage tree in the past few weeks. I don't yet know if other drivers are affected and just wanted to start the ball rolling on information collection.

**Comment by joecool1029** [comment]
NOPE, it was actually a gentoo bug, fixed upstream: https://bugs.gentoo.org/872716

Closing.

**Comment by stefan-langenmaier** [comment]
Thanks for the follow-up and the reference to the ticket!
