### ISSUE TITLE
Add support for HL-5470DW series

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [stefan-langenmaier/brother-overlay#14]
Would it be possible to add the [drivers for the Brother HL-5470DW](http://support.brother.com/g/b/downloadtop.aspx?c=us&lang=en&prod=hl5470dw_us_eu_as)?

**Comment by stefan-langenmaier** [comment]
Hi,

To me it looks like this printer should be supported by the generic driver. Could you please test _**net-print/brother-genml1-bin**_ and report back if it's working.

Best regards
Stefan

**Comment by stefan-langenmaier** [comment]
The print has now an ebuild (depending on net-print/brother-genml1-bin).
