### ISSUE TITLE
Merge packages into brother-genml1-bin

### ISSUE THREAD

**Issue by stefan-langenmaier** [stefan-langenmaier/brother-overlay#17]
Some packages are a duplication of the generic printer driver. This causes conflicts in their installation and is duplication of effort.

* Find a way to merge them nicely into the this driver.
* Can there be something done with the naming as it might not be easy to find this driver with its current name?

**Comment by fonic** [comment]
How about adding virtual packages for each supported printer / scanner that does nothing except pulling the generic driver (or brscan3/brscan4 respectively) as a dependency?

That's how the virtual packages work, e.g. `/usr/portage/virtual/jdk`.

**Comment by stefan-langenmaier** [comment]
Honestly I haven't thought about about the approach to have individual packages that pull in the generic driver. I like the idea!

This way each package could have its own description (the elogs that show how to setup the printer). And at the same time the names of the packages would be more clear and the description in the generic package could be reduced.

Just to clarify this a bit. I'm not sure if virtual packages is the best name here, as virtuals normally give you a list of alternatives with a default (package and version). Here it's the other way around, if I understood correctly. There will be multiple packages, that all depend on the same driver. So I think a line with RDPEND should do the trick.

What do you think?

**Comment by fonic** [comment]
> This way each package could have its own description (the elogs that show how to setup the printer). And at the same time the names of the packages would be more clear and the description in the generic package could be reduced.

Exactly.

You're right, 'virtual' was the first term that came to my mind. I think calling them 'meta' packages is more appropriate.

Regarding the content of the meta packages, I guess something like this would suffice:
```EAPI="6"
DESCRIPTION="Brother printer/scanner driver for <model>"
SLOT="0"
KEYWORDS="amd64 x86"
RDEPEND="<driver/scanner package>"
pkg_postinst() {
        einfo "<model-specific message>"
}
```

**Comment by stefan-langenmaier** [comment]
Yes, this looks how I understood it.

**Comment by fonic** [comment]
How about this?
[brother-generator.sh.txt](https://github.com/stefan-langenmaier/brother-overlay/files/259864/brother-generator.sh.txt)

**Comment by stefan-langenmaier** [comment]
Wow that was fast! Parsing the output is really nice. Definitively more than a start.

But I like to complicate the things a little bit more. :) When you mentioned the meta packages I had "more" functionality in mind. The package should be per device so you can install the scanner and printer  (and fax and...) at the same time.
This makes an automatic script a lot harder as there are devices with just a printer and printer and scanner with version 3 and printer and scanner with version 4 and probably other combinations.

I have created pull request #18 with a package for one printer/scanner. I also gave you the rights to commit and push to the repository. If you like the idea you could commit your script and we can work together on it.

**Comment by fonic** [comment]
Thank you :)

Actually, I would recommend against meta packages for both scanner/printer for multiple reasons:

1. It violates the KISS principle which is the foundation of everything in Linux
2. It complicates things for the user. If a user wants to install only the scanner or printer driver on his machine, he would have to change USE flags etc.
3. It makes maintaining the packages/ebuilds and thus your whole repository way more complicated

One package for scanner and one for printer is just way simpler for everyone. Also keep in mind that the packages are named the same (e.g. 'media-gfx/brother-mfc7440n-bin' and 'net-print/brother-mfx7440n-bin'), so portage will suggest both when running 'emerge brother-mfc7440n-bin' and the user is automatically informed that there are two packages available for his device.

**Comment by fonic** [comment]
I uploaded the generator. For now it creates separate packages for brscan3, brscan4 and brgenml1. If you still want to create packages for scanner+printer we can of course modify it to do so.

Please note the switch which I implemented for debugging/testing.

**Comment by stefan-langenmaier** [comment]
Thanks for the feedback. I would like to argue point 1 and 2, but I have to
admit point 3 and especially the point you raise in the text afterwards.

I will delete my pull request and look at your commit this evening when I'm
back.

**Comment by fonic** [comment]
Just to make sure you don't get me wrong: I'm not arguing against or for something - we both know there are always multiple solutions to a problem. I just wanted to point out that all-in-one-packages are a lot of effort vs. little benefit from my point of view.

**Comment by stefan-langenmaier** [comment]
No, I'm totally okay with the approach you have proposed. And yes there is
always a tradeoff to make. :)

**Comment by stefan-langenmaier** [comment]
I fixed some issues (fixed some depdencies and made repoman happy) in the script and I did some clean up for the base packages brother-genml1-bin and brother-scan4-bin. Maybe you can check it.

**Comment by fonic** [comment]
Looking good! I fixed a minor issue regarding dollar signs and added the metadata stuff to the debug output.

**Comment by stefan-langenmaier** [comment]
Impressive numbers! I would say you should go ahead an create a commit with all these packages. Maybe first in a branch apart.

One thing I haven't checked yet if there are conflicts with existing packages like MFC-7460DN. If yes what should be done in this case. I think there the version is already at 3.x.

**Comment by stefan-langenmaier** [comment]
As I haven't back from you I merged the created ebuild myself. I hope you are okay with it.
