### ISSUE TITLE
Support for HL-3150CDW

### ISSUE THREAD

**Issue by chriscpritchard** [stefan-langenmaier/brother-overlay#24]
Would you be able to add support for theHL-3150CDW?

Thank you

**Comment by stefan-langenmaier** [comment]
Hi,

I added the printer.
Would you be so nice to give me some feedback as I don't have the hardware so there is no way for me to test it.

Best regards
Stefan

**Comment by stefan-langenmaier** [comment]
No feedback so far. Closing it.
