### ISSUE TITLE
Brother-hl1118 support.

### ISSUE THREAD

**Issue by lebarondemerde** [stefan-langenmaier/brother-overlay#35]
Hello,

Please, may you consider add in an ebuild for Brother HL-11xx series?

This one support: Brother HL-1110, HL-1110R, HL-1111, HL-1112, HL-1112R, HL-1118.

There is a [PKGBUILD](https://aur.archlinux.org/packages/brother-hl1118/) on Arch Linux AUR.

Thank you!

**Comment by stefan-langenmaier** [comment]
Hi,

the printer looks similar to [hl3140cw](https://github.com/stefan-langenmaier/brother-overlay/blob/master/net-print/brother-hl3140cw-bin/brother-hl3140cw-bin-1.1.4.ebuild). It could be copied from that and should work with a couple replacements. If you want you can make a pull request. If you need help just ask. Otherwise I hope I can do it on the weekend.

**Comment by stefan-langenmaier** [comment]
I added the model. Please let me know if it works as I can't really test it.

**Comment by lebarondemerde** [comment]
Thank you! Sorry about the delay, just now I see your comments.

I do not have access to the printer right now, but I will try it ASAP.

**Comment by lebarondemerde** [comment]
Hi,

Just a minor typo on ebuild line 55. Where it read:

`( cd "${D}/usr/libexec/cups/filter/" && ln -s ../../../../opt/brother/Printers/HL1110/lpd/filter_**hl**1110 brother_lpdwrapper_HL1110 ) || die`

should be indeed:

`( cd "${D}/usr/libexec/cups/filter/" && ln -s ../../../../opt/brother/Printers/HL1110/lpd/filter_**HL**1110 brother_lpdwrapper_HL1110 ) || die`

Other than that it is working quite fine.

Thank you!

**Comment by stefan-langenmaier** [comment]
Is it causing a problem or why has it to be changed?

**Comment by lebarondemerde** [comment]
Oh, sorry, it was not printing because the file could not be found by Cups at /usr/libexec/cups/filter/ due to the sym-linked file being with lowercase "hl".

Thank you!

**Comment by stefan-langenmaier** [comment]
I included your correction.

Thanks for your feedback. I'm closing the issue. Don't hesitate to reopen if you an issue.

Best regards
Stefan
