### ISSUE TITLE
dcp-1610w-bin is empty.

### ISSUE THREAD

**Issue by crocket** [stefan-langenmaier/brother-overlay#39]
The ebuild file for dcp-1610w-bin doesn't download and unpack rpm files.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brother-dcp1610w might be useful as a reference.

**Comment by stefan-langenmaier** [comment]
The ebuild in the repo is only for the scanner part. It looks like there is no ebuild for the printer part. I'll try to have something over the weekend.

**Comment by stefan-langenmaier** [comment]
I added now also a printer driver net-print/brother-dcp1610w-bin. Could you please report back if the printer is working as I cannot test it.

Thanks!

**Comment by crocket** [comment]
I installed both net-print/brother-dcp1610w-bin and media-gfx/brother-dcp1610w-bin

CUPS says

> File "/usr/libexec/cups/filter/brother_lpdwrapper_DCP1610W" not available: No such file or directory

I'll update this comment after testing scanner.

**Comment by stefan-langenmaier** [comment]
To me it looks more like the filename (but not the path is incorrect).
I update the ebuild. Could you try it again?

**Comment by crocket** [comment]
With your last update, I can send printing commands to DCP-1610W.

I can confirm that I can print to and scan from DCP-1610W.

Thanks for your effort. I'm closing this issue.

**Comment by stefan-langenmaier** [comment]
Thanks for your feedback!
