### ISSUE TITLE
!!! Section 'brother-overlay' in repos.conf has name different from repository name 'Brother-printers' set inside repository

### ISSUE THREAD

**Issue by landscape69** [stefan-langenmaier/brother-overlay#6]
!!! Section 'brother-overlay' in repos.conf has name different from repository name 'Brother-printers' set inside repository

**Comment by stefan-langenmaier** [comment]
I'm not sure what the issue is? Are you saying the value in "profiles/repo_name" and the name in "repositories.xml" should be identical.
Sure I can change that.

I'm interested. What are the implications of that?

**Comment by landscape69** [comment]
well i want only to inform u about this warning. 

btw can u add some other brother printers in this overlay too?

i need the 7055 and 7055w 

http://support.brother.com/g/b/producttop.aspx?c=de&lang=de&prod=dcp7055_all

danke dir herzlich

**Comment by stefan-langenmaier** [comment]
The DCP-7055 should also work with the generic driver from the repo "net-print/brother-genml1-bin".

Unfortunately I cannot test it, as I don't have the printer.

Ich würde mich freuen wenn du berichten könntest, ob es für dich funktioniert.

**Comment by landscape69** [comment]
i will test ASAP.

danke dir für die info. ich werde es so bald es mir möglich ist testen und hier feed back geben. es ist echt schade, dass cups das nichts schon längst untersützt.

**Comment by stefan-langenmaier** [comment]
I updated the instructions so the installation should be more clear.

No feedback on the functionality so far.
