### ISSUE TITLE
net-print/brother-genml1-bin should require multilib

### ISSUE THREAD

**Issue by joecool1029** [stefan-langenmaier/brother-overlay#7]
I run pure 64-bit.  This package will not work here, and printing will seem like it's working but silently fail to end user.  (even if 32-bit emulation support is there, still missing some lib)

Maybe ebuild should have dependency or some other sort of warning.

I spent some hours trying to figure out why it was silently failing on my system and this was why.  At least the scanning tool works, but I have to use cups generic PCL driver for printer (works pretty ok)

**Comment by stefan-langenmaier** [comment]
Thanks for the feedback. Yes I use multilib and the IA32_EMULATION kernel option with my system.

I'm no expert here, but the executables are all statically compiled and I thought I would be enough to have the kernel option.

I would be interested to find out more about this issue. Could you reinstall the package and try to execute the following files and attach the errors/output here

/opt/brother/Printers/BrGenML1/lpd/rawtobr3
/opt/brother/Printers/BrGenML1/lpd/brprintconflsr3

aswell as

ldd /opt/brother/Printers/BrGenML1/lpd/rawtobr3
ldd /opt/brother/Printers/BrGenML1/lpd/brprintconflsr3

**Comment by stefan-langenmaier** [comment]
I checked the ldd output on my system and it looks like multilib is necessary. You're right the ebuild should require multilib.

I already asked Brother for the source code of this package but they are only referring to the old sources that are available on their site. It's a little bit sad.

**Comment by joecool1029** [comment]
I'll see if I can bug them a little more about this.  It is 2015, no-multilib systems have been pretty common now for at least the past 5 years.  Even adobe-flash doesn't depend on 32-bit libs anymore (never thought I'd see that day)

**Comment by stefan-langenmaier** [comment]
let me now if you hear something from Brother :)
