### ISSUE TITLE
Brother MFC-6490CW CUPS and LPR support

### ISSUE THREAD

**Issue by mehw** [stefan-langenmaier/brother-overlay#72]
Hi!

The [printer-drivers overlay](https://cgit.gentoo.org/proj/printer-drivers.git/) had been [recently removed from repositories.xml](https://cgit.gentoo.org/data/api.git/commit/files/overlays/repositories.xml?id=b766404a47218209081e32ab0c90ee87175eb7fd).

I do have a Brother MFC-6490CW printer/scanner (inherited from my grandpa), and I'm happy to see that [brother-overlay provides a way to install the scanner driver](https://github.com/stefan-langenmaier/brother-overlay/tree/master/media-gfx/brother-mfc6490cw-bin).

What about [CUPS](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-cups) and [LPR](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-lpr) drivers...?

Is it possible/useful to add them to brother-overlay?

Also, MFC-6490CW isn't listed in the [Gentoo's Brother networked printer guide](https://wiki.gentoo.org/wiki/Brother_networked_printer).

A quick CUPS/LPR drivers fix is to add the printer-drivers overlay back via a [layman's overlay xml file](https://wiki.gentoo.org/wiki/Layman#Missing_repository.xml_file):

**_/etc/layman/overlays/printer-drivers.xml_**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repositories SYSTEM "/dtd/repositories.dtd">
<repositories xmlns="" version="1.0">
  <repo quality="experimental" status="unofficial">
    <name>printer-drivers</name>
    <description lang="en">User-submitted ebuilds for printer drivers</description>
    <homepage>https://cgit.gentoo.org/proj/printer-drivers.git/</homepage>
    <owner type="project">
      <email>printing@gentoo.org</email>
      <name>Gentoo printing team</name>
    </owner>
    <source type="git">https://anongit.gentoo.org/git/proj/printer-drivers.git</source>
    <source type="git">git://anongit.gentoo.org/proj/printer-drivers.git</source>
    <source type="git">git+ssh://git@git.gentoo.org/proj/printer-drivers.git</source>
    <feed>https://cgit.gentoo.org/proj/printer-drivers.git/atom/</feed>
    <!-- <feed>https://cgit.gentoo.org/proj/printer-drivers.git/rss/</feed> -->
  </repo>
</repositories>
```

Another way explained in [brother-overlay's README.md](https://github.com/stefan-langenmaier/brother-overlay/blob/master/README.md) is via a [portage's ebuild repository](https://wiki.gentoo.org/wiki//etc/portage/repos.conf#External_ebuild_repository):

**_/etc/portage/repos.conf/printer-drivers.conf_**
```conf
[printer-drivers]
location = /usr/local/portage/overlays/printer-drivers
sync-type = git
sync-uri = https://anongit.gentoo.org/git/proj/printer-drivers.git
auto-sync = yes
```

What do you think? Should the Brother MFC-6490CW's [CUPS](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-cups) and [LPR](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-lpr) drivers be added to brother-overlay?

**Comment by stefan-langenmaier** [comment]
Hi @mehw ,

sorry I haven't responded yet and thanks a lot for your very detailed issue.
First of all I didn't even know about the printer-drivers overlay. :)
In general I would be more than happy to add an ebuild for this printer to the overlay.

**Comment by mehw** [comment]
Hi @stefan-langenmaier,

> sorry I haven't responded yet and thanks a lot for your very detailed issue.

don't worry I'm pretty busy too...

> In general I would be more than happy to add an ebuild for this printer to the overlay.

Should I open a PR? I don't want to take the credit for ebuilds which are alredy in the printer-drivers overlay...

**brother-mfc6490cw-cups**:
- [CUPS ebuild](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-cups/brother-mfc6490cw-cups-1.1.2_p2.ebuild)
- [CUPS metadata.xml](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-cups/metadata.xml)
- [CUPS Manifest](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-cups/Manifest)

**brother-mfc6490cw-lpr**:
- [LPR ebuild](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-lpr/brother-mfc6490cw-lpr-1.1.2_p2.ebuild)
- [LPR metadata.xml](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-lpr/metadata.xml)
- [LPR Manifest](https://cgit.gentoo.org/proj/printer-drivers.git/tree/net-print/brother-mfc6490cw-lpr/Manifest)

Let me know what you plan to do. Thanks!

**Comment by stefan-langenmaier** [comment]
Hey,

if you can open a pull request that'd be excellent.
Currently all printer ebuilds in this repo install the lpr and cups drivers together and I'd like to keep with this for the sake of consistency.
Do you think you can create a "merged" ebuild. I'm sure you can mention where you have the original idea/ebuilds from. :) But technically/license-wise it shouldn't be an issue to use them in this repository aswell.

Cheers!

**Comment by mehw** [comment]
> if you can open a pull request that'd be excellent.

Ok @stefan-langenmaier... PR #75 created...

> Do you think you can create a "merged" ebuild. I'm sure you can mention where you have the original idea/ebuilds from. :)

All the above done.

So, I'm going to close this issue now. The conversation may continue in the PR.

Cheers!
