### ISSUE TITLE
Errors when using brscanconfig4 to query for printers

### ISSUE THREAD

**Issue by mortenlj** [stefan-langenmaier/brother-overlay#87]
I'm trying to get my Brother DCP-7065DN working as a scanner. When I try to add the device, I get no errors, but when I try querying to see if it was added I get some errors and nothing more:

```
# brsaneconfig4 -q
sh: /opt/brother/scanner/brscan4/brscan_gnetconfig: No such file or directory
sh: /opt/brother/scanner/brscan4/brscan_cnetconfig: No such file or directory
sh: /opt/brother/scanner/brscan4/brscan_gnetconfig: No such file or directory
sh: /opt/brother/scanner/brscan4/brscan_cnetconfig: No such file or directory
```
It looks like a couple files are missing, but I don't know where they should come from?

Installed verisons:
```
yeager ~ # eix -A media-gfx/brother-dcp7065dn-bin
[I] media-gfx/brother-dcp7065dn-bin [1]
     Available versions:  1.0
     Installed versions:  1.0(kl. 10.03 +0100 29. okt. 2019)
     Homepage:            http://support.brother.com
     Description:         Scanner driver for Brother DCP-7065DN (brscan4)

[1] "brother-overlay" /var/lib/layman/brother-overlay
yeager ~ # eix -A media-gfx/brother-scan4-bin
[I] media-gfx/brother-scan4-bin [1]
     Available versions:  0.4.4-r3^ms 0.4.4-r4^ms (~)0.4.4-r5^ms (~)0.4.6-r1^ms (~)0.4.6-r2^ms (~)0.4.8^ms {usb}
     Installed versions:  0.4.8^ms(kl. 10.04 +0100 29. okt. 2019)(-usb)
     Homepage:            http://support.brother.com/g/s/id/linux/en/index.html
     Description:         Brother scanner tool version 4

[1] "brother-overlay" /var/lib/layman/brother-overlay
```

If I try adding it again I get an error about it already being registered, so I guess it worked to add it. If nothing else, it would be nice to find a way to silence those errors to avoid confusing the user.

**Comment by stefan-langenmaier** [comment]
Hi Morten,

thanks for your report. It looks like the ebuild didn't install the executables. I have added them now.
I don't own a scanner with this driver so I'd be nice if you can let me know if it's working for you.

Best regards,
Stefan

**Comment by mortenlj** [comment]
I re-emerged this ebuild now (you didn't bump the version), and got the extra binaries. When querying now, I get a dialog showing the added scanners, and no errors. Looks like it's working fine, thanks for the fix.
