### ISSUE TITLE
media-gfx/brother-scan4-bin should depend on net-dns/avahi

### ISSUE THREAD

**Issue by fordfrog** [stefan-langenmaier/brother-overlay#92]
when adding new scanner using brsaneconfig4 command, the command fails because it cannot find /usr/lib/libavahi-client.so.3. adding net-dns/avahi to RDEPEND should fix it. i have media-gfx/brother-scan4-bin-0.4.8 installed but i suppose other versions are affected aswell...

**Comment by stefan-langenmaier** [comment]
Thanks for your report and sorry for the late reply. I have added an `avahi` USE-flag for this dependency.
