### ISSUE TITLE
Cups-filter PDF

### ISSUE THREAD

**Issue by JStyle21** [stefan-langenmaier/brother-overlay#96]
Hi,

This might be a strange question but i've used this overlay for my printer and it can't seem to print PDF files off the browser, the job log shows the following message:
 "Use "pdftops-renderer" option (see cups-filters README file) to use Ghostscript or MuPDF for the PDF -> PostScript conversion."

I've found the following command:

```
lpstat -v
lpadmin -p <printer> -o pdftops-renderer-default=gs

```

I've tried gs and mupdf but gs gives an empty page while mupdf give an error "Level 3 PostScript not supported by mutool"

Any ideas?

**Comment by stefan-langenmaier** [comment]
So this is only an issue if you print from the browser? Other applications are working?

Where did you find these commands? What is their output?

I'm a little bit clueless. :)

**Comment by JStyle21** [comment]
> So this is only an issue if you print from the browser? Other applications are working?
Yes, only Firefox seems to have an issue local apps work fine.
Initially i thought it was due to PDF problems in the browser but i tried to print web pages and it's the same issue.

I can only say that the PDF job from Firefox was 600kb while the same file from a PDF program was only 120kb so there is some kind of conversion there.

> Where did you find these commands? What is their output?
When i looked at the completed jobs in Cups i saw the error i mentioned which made me think it is something that isn't set so i googled a lot and ended up in a thread that mentioned those commands.
https://forums.gentoo.org/viewtopic-t-999916-start-0.html
The first one prints the name of all available printers while the second sets the value of pdftops which is the filter used to convert PDF file while printing.
While pdftops has many values the only available on my machine are ghostscript mupdf and none, i've mentioned the result of that attempt, mupdf give another error while GS prints an empty page like before.

I should also mention i've checked all my packages and they all have the right flags so everything seems to be connected and should work, i even checked allow printing from the internet inside of cups but it didn't help

Sorry to drop this on you, it's ok if you don't know, i just thought i would ask since i'm having this issue for quite a while now and i've used this overlay for my printer driver in Gentoo.

**Comment by stefan-langenmaier** [comment]
> I can only say that the PDF job from Firefox was 600kb while the same file from a PDF program was only 120kb so there is some kind of conversion there.

When a browser displays a PDF file directly it is rendered to an image. So when you print this you print the rendered image. In general it's not a good idea to print PDFs directly from the browser. It's slower as the size of the document is bigger, but especially the quality is not as good.

> Sorry to drop this on you, it's ok if you don't know, i just thought i would ask since i'm having this issue for quite a while now and i've used this overlay for my printer driver in Gentoo.

Unfortunately I have no idea what's the problem here (or in the link to the forum), so I'm probably the wrong person. :)

**Comment by JStyle21** [comment]
It's ok, i appreciate the time you took to reply on this.

I"l close it as it is and try my luck elsewhere.
